Mods to the recoder. Input to ease changing the length of the audio file. Date stamped to the wav filename
kamilsss655/ESPRI pull request #62
Opened 2024-07-24 20:10 UTC by EA5JQP

I did some modifications on the frontend for the Recorder:
1- Added an input to ease changing the length of the audio file. With the slider we can go up to 10 min, but up to the maximum can be introduce in the input field.
2- In order to avoid rewriting the same audio file, the date and time is added to the wav filename.

2024-08-02 12:18 UTC, kamilsss655 reviewed
LGTM, left some comments.

2024-08-02 12:18 UTC, kamilsss655 commented on frontend/src/stores/recorder.ts
> +const formattedTimeStamp = date.formatDate(timeStamp, 'YYYYMMDD_HHmmss')
Can you extract `formattedTimeStamp` logic to some helper file so implementation is not repeated across different files?

2024-08-02 12:18 UTC, kamilsss655 commented on frontend/package-lock.json
> -      "integrity": "sha512-b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==",
I don't think this PR requires changes to `frontend/package-lock.json`

2024-08-02 20:40 UTC, EA5JQP commented
I made the suggested changes. Thanks a lot!

2024-08-03 08:51 UTC, kamilsss655 requested changes

2024-08-03 08:51 UTC, kamilsss655 commented on frontend/src/helpers/Time.ts
> +export const useFormattedTimeStamp = (): string => {
Good! Couple of remarks:

1. Let's refactor this function so it accepts `Date` parameter, and at call sites pass `Date.now()` as a param to it.  That way we can use it in the future for formatting other dates.
2. Maybe rename the function to better describe it's function i.e `formatDate` or `formatTimestamp` ?

2024-08-04 14:02 UTC, kamilsss655 commented on frontend/src/helpers/Time.ts
> +export const formatTimestamp  = (dateInput: Date): string => {
:+1:

2024-08-04 14:09 UTC, kamilsss655 requested changes
The code looks good.

I did test it now and found a bug where user can enter a higher value, but the slider will display the max of 600. In terms of user experience this is confusing because now there are 2 values displayed and user will not know which one is going to be respected.
![image](https://github.com/user-attachments/assets/6f9ac17b-9cc1-4f37-8dd4-36f7b6ef5193)

To remedy this I'd suggest a different approach where there is only a slider, but a user can select units of:
* seconds
* minutes
* hours

This would solve granularity problem without causing user confusion.

What do you think?

2024-08-04 14:48 UTC, EA5JQP commented
Yes, I agree it is confussing. My initial idea was to limit the slider up to 10 min to make it simpler, but still keeping the possibility of editing via the q-input. A quick "fix" would be to remove the value in the slider itself (600 in your screenshot) since it is already shown in the q-input.

Regarding one slider and three units, will the user be able to switch units? So if I want 1h 30min 40sec I would have move the slider and switch the unit a couple of times? In this case, I would use directly three different sliders.

2024-08-04 15:06 UTC, kamilsss655 commented
I like your three sliders idea!

2024-08-06 21:04 UTC, EA5JQP commented
Now we have three sliders. Somehow @input didn't update the value automatically when moving the slider, but @change works as well. Probably there is much room for improvement on the presentation side.

2024-08-07 17:29 UTC, kamilsss655 commented
I like the look with 3 sliders!

Couple of suggestions:
* maybe consider adding `label-always` to sliders so the user see the current value (total duration in seconds in not that comprehensive to humans, especially if the user selected couple of hours)
* also when I select some values with a slider and leave the page and then come back they are initialized as 0
  * perhaps we should move seconds, minutes, hours to `store` so they are kept in between user navigating to different pages?

2024-08-07 20:32 UTC, EA5JQP commented
Thank you for the suggestions!

Here are the changes:
- I like how `label-always` show the current value, so I removed the `div` with the total number of seconds. 
- The value of seconds, minutes and hours are now stored. For this I created a new file: stores/duration.ts

2024-08-08 09:30 UTC, merged

2024-08-08 09:36 UTC, kamilsss655 commented
I've done some refactoring and cleanup and merged it in. Should be in next release!